title: Eno Leriand
url: "https://z0rs.github.io"
baseurl: "/me/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://z0rs.github.io"
footer_text: "Eno Leriand"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/research/"
 - name: "LinkeIn"
   link: "https://www.linkedin.com/in/enoleriand/"
 - name: "Twitter"
   link: "https://twitter.com/0x3n0"
 - name: "Tryhackme"
   link: "https://tryhackme.com/p/0x3n0"
 - name: "HackTheBox"
   link: "https://web.archive.org/web/20220301034757/https://app.hackthebox.com/profile/381523"
