title: Eno Leriand
url: "https://z0rs.github.io"
baseurl: "/research/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://3n0.us"
footer_text: "Eno Leriand"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/research/"
 - name: "Resume"
   link: "Myresume.pdf"
 - name: "Contact"
   link: "contact"
